spring:
  application:
    name: MailMcpClient
  main:
    web-application-type: none
  jackson:
    default-property-inclusion: non_null
  ai:
    openai:
      base-url: https://api.deepseek.com/v1
      api-key: sk-92a139dbea674ab2a3f1d3025e407787
      chat:
        completions-path: /chat/completions
        options:
          model: 'deepseek-chat'
    mcp:
      client:
        enabled: true
        request-timeout: 30s
        initialized: true
        sse:
          connections:
            mail-mcp-server:
              url: http://localhost:8088

server:
  port: 766